// <auto-generated />
using System;
using Database.HotContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.HotContext.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240306160433_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Date.Models.Entities.Finance.BudgetAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BudgetAccountTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(2215),
                            CreatedBy = "System",
                            Key = "labelActivities",
                            UpdatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(2216),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(2220),
                            CreatedBy = "System",
                            Key = "labelCar",
                            UpdatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(2221),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(2222),
                            CreatedBy = "System",
                            Key = "labelCarryOfLastMonth",
                            UpdatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(2223),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(2224),
                            CreatedBy = "System",
                            Key = "labelCommunication",
                            UpdatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(2225),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(2226),
                            CreatedBy = "System",
                            Key = "labelGastronomy",
                            UpdatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(2227),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(2230),
                            CreatedBy = "System",
                            Key = "labelIncome",
                            UpdatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(2230),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(2232),
                            CreatedBy = "System",
                            Key = "labelReside",
                            UpdatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(2232),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(2233),
                            CreatedBy = "System",
                            Key = "labelShopping",
                            UpdatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(2234),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(2235),
                            CreatedBy = "System",
                            Key = "labelTobacco",
                            UpdatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(2236),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(2238),
                            CreatedBy = "System",
                            Key = "labelVacation",
                            UpdatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(2239),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Date.Models.Entities.Finance.BudgetDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ParentAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BudgetDepartmentTable");
                });

            modelBuilder.Entity("Date.Models.Entities.Finance.BudgetDepartmentAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BudgetAccountId")
                        .HasColumnType("int");

                    b.Property<int>("BudgetDepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPayment")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BudgetDepartmentAccountTable");
                });

            modelBuilder.Entity("Date.Models.Entities.Log.LogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("ExMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StackTrace")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LogTable");
                });

            modelBuilder.Entity("Date.Models.Entities.User.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("UserRolesJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(1629),
                            CreatedBy = "System",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "exampleuser@gmx.com",
                            EmailConfirmed = false,
                            FirstName = "",
                            IsActive = true,
                            LastName = "",
                            Password = "UEBzc3dvcmRlNGI4NzJlNC00ZmNjLTRhNmMtODEzNi1iZTM3YzliYmJhOGI=",
                            Salt = "e4b872e4-4fcc-4a6c-8136-be37c9bbba8b",
                            UserRolesJson = "{\"Name\":\"System Admin\",\"Description\":\"System Admin User\",\"Id\":3,\"CreatedBy\":\"System\",\"CreatedAt\":\"2024-03-06T16:04:33.0461631Z\",\"UpdatedBy\":null,\"UpdatedAt\":null}"
                        });
                });

            modelBuilder.Entity("Date.Models.Entities.User.UserRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserRolesTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(1132),
                            CreatedBy = "System",
                            Description = "Default User",
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(1139),
                            CreatedBy = "System",
                            Description = "Admin User",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 6, 16, 4, 33, 46, DateTimeKind.Utc).AddTicks(1140),
                            CreatedBy = "System",
                            Description = "System Admin User",
                            Name = "System Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
